# Site settings
author: Alycia
title: Waves, First Project
header-img: img/home-bg.png
email: amhall25@gmail.com
copyright_name: Alycia
description: > # this means to ignore newlines until "baseurl:"
  CLI to find local beaches
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  amhall25

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
